production:
        adapter: mysql2
        database: redmine
        host: redmine
        username: root
        password: ""
        encoding: utf8

development:
        adapter: mysql2
        database: redmine2
        host: localhost
        username: root
        password: ""
        encoding: utf8

